const sheetId = "1anWPcNxxjs9bMjxgwey9P8FNm4_usHGr";
const tabs = ["Players", "Matches", "Appearances", "Goals"];
let language = new URLSearchParams(window.location.search).get("lang") === "ja" ? "ja" : "en";
let dashboardData;
let attendanceSearch = "";

const translations = {
  en: { officialWebsite: "Official Soccer Top Team · Est. 1868", officialTeam: "YC&AC Official Soccer Top Team", season: "YC&AC Football · Season 2026", report: "YC&AC Pulse", intro: "YC&AC's official Top Team. Follow our season, join team events, and stay connected with the squad.", heroNote: "Proudly representing Yokohama Country & Athletic Club", about: "About the Team", introductionOne: "YC&AC Pulse is built on ambition, structure and the spirit of the Club.", introductionTwo: "YC&AC Pulse brings together players of diverse backgrounds with a shared goal: to compete, improve and represent YC&AC with pride.", introductionThree: "More than just a team, it is a platform for committed football, strong camaraderie and continuous growth, both on and off the pitch.", navSeason: "Season", navStandings: "Standings", navSchedule: "Schedule", scheduleLink: "Team Scheduling & Event Sign Up", standingsLink: "TML Division 3 Standings", clubLink: "YC&AC Club Website", standardSignup: "Standard Sign Up", prioritySignup: "YC&AC Priority", seasonStats: "Season Statistics", footer: "YC&AC Pulse · Official Soccer Top Team of Yokohama Country & Athletic Club", record: "Record", goalsFor: "Goals for", goalsAgainst: "Goals against", cleanSheets: "Clean sheets", upcoming: "Upcoming", fixtures: "Next Matches", kickoff: "Kickoff", matchday: "Season", results: "Results", attack: "Attack", contributions: "Goal Contributions", availability: "Availability", attendance: "Attendance", player: "Player", position: "Position", attendanceRate: "Attendance", summary: "Summary", searchPlayer: "Search player", swipeHint: "Swipe left and right to view match columns.", starter: "Starter", substitute: "Substitute", scored: "Scored", cleanSheet: "Clean sheet (GK)", contact: "Contact", contactTitle: "Contact YC&AC Pulse", contactCopy: "Send the team a message about fixtures, events, or the club.", name: "Name", email: "Email", message: "Message", sendMessage: "Send message", instagram: "Instagram", instagramTitle: "Follow YC&AC Pulse", instagramCopy: "Match graphics, team news, and moments from the squad. Contact the team directly on Instagram.", versus: "vs", goals: "goals", assists: "assists", liveData: "Live data", matchesRecorded: "matches recorded", unavailable: "Data is currently unavailable" },
  ja: { officialWebsite: "公式サッカートップチーム · Est. 1868", officialTeam: "YC&AC 公式サッカートップチーム", season: "YC&AC フットボール · 2026シーズン", report: "YC&AC Pulse", intro: "YC&ACの公式トップチーム。シーズンの記録、チームイベント、チームの最新情報をご覧ください。", heroNote: "横浜カントリー＆アスレティッククラブを代表するトップチームです", about: "チームについて", introductionOne: "YC&AC Pulseは、向上心、組織力、そしてクラブの精神を礎としています。", introductionTwo: "多様なバックグラウンドを持つ選手が集まり、競い合い、成長し、YC&ACを誇りを持って代表するという共通の目標を掲げています。", introductionThree: "単なるチームではなく、真摯なフットボール、強い仲間意識、そしてピッチ内外での継続的な成長のための場です。", navSeason: "シーズン", navStandings: "順位表", navSchedule: "日程", scheduleLink: "チーム日程・イベント参加申込", standingsLink: "TML Division 3 順位表", clubLink: "YC&AC クラブ公式サイト", standardSignup: "通常申込", prioritySignup: "YC&AC 優先申込", seasonStats: "シーズン成績", footer: "YC&AC Pulse · 横浜カントリー＆アスレティッククラブ公式サッカートップチーム", record: "戦績", goalsFor: "得点", goalsAgainst: "失点", cleanSheets: "無失点試合", upcoming: "次の試合", fixtures: "今後の試合", kickoff: "キックオフ", matchday: "シーズン", results: "リザルト", attack: "攻撃", contributions: "ゴール貢献", availability: "出席状況", attendance: "出席", player: "選手", position: "ポジション", attendanceRate: "出席率", summary: "集計", searchPlayer: "選手を検索", swipeHint: "左右にスワイプして試合の列を表示できます。", starter: "先発", substitute: "途中出場", scored: "ゴール", cleanSheet: "無失点（GK）", contact: "お問い合わせ", contactTitle: "YC&AC Pulse へのお問い合わせ", contactCopy: "試合、イベント、チームに関するお問い合わせをお送りください。", name: "お名前", email: "メールアドレス", message: "メッセージ", sendMessage: "メッセージを送信", instagram: "Instagram", instagramTitle: "YC&AC Pulse をフォロー", instagramCopy: "試合グラフィック、チームニュース、チームの瞬間をお届けします。Instagramからチームへ直接お問い合わせください。", versus: "vs", goals: "ゴール", assists: "アシスト", liveData: "最新データ", matchesRecorded: "試合を記録", unavailable: "データを読み込めません" },
};

function t(key) { return translations[language][key]; }
translations.en.squadPicker = "Squad Picker";
translations.ja.squadPicker = "メンバー選出";
function applyLanguage() { document.documentElement.lang = language; document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); }); document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); }); document.querySelector("#squad-picker-link").href = language === "ja" ? "squad-picker.html?lang=ja" : "squad-picker.html"; const localeToggle = document.querySelector("#locale-toggle"); localeToggle.textContent = language === "en" ? "日本語" : "English"; localeToggle.href = language === "en" ? "?lang=ja" : "./"; localeToggle.lang = language === "en" ? "ja" : "en"; document.title = language === "en" ? "YC&AC Pulse | Official Team Website" : "YC&AC Pulse | 公式チームサイト"; }

async function getSheet(tab) {
  const callback = `ycacSheet_${tab.replace(/\W/g, "_")}_${Date.now()}`;
  const query = new URLSearchParams({ tqx: `out:json;responseHandler:${callback}`, sheet: tab });
  const json = await new Promise((resolve, reject) => {
    const script = document.createElement("script");
    const cleanup = () => { script.remove(); delete window[callback]; };
    window[callback] = (response) => { cleanup(); if (response.status !== "ok") { reject(new Error(`Could not load ${tab}`)); return; } resolve(response); };
    script.onerror = () => { cleanup(); reject(new Error(`Could not load ${tab}`)); };
    script.src = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?${query}`;
    document.head.append(script);
  });
  let headers = json.table.cols.map((column) => column.label);
  let rows = json.table.rows;
  // Google occasionally returns a first-row header as data for imported tabs.
  if (headers.every((header) => !header) && rows.length) {
    headers = rows[0].c.map((cell) => cell?.v ?? "");
    rows = rows.slice(1);
  }
  return rows.map((row) => Object.fromEntries(headers.map((header, index) => [header, row.c[index]?.v ?? ""])));
}

function playerName(players, id) { return players.get(id)?.display_name || id; }
function formatDate(value) { return new Intl.DateTimeFormat(language === "ja" ? "ja-JP" : "en", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`)); }

function render(data) {
  const players = new Map(data.Players.filter((player) => player.active !== false).map((player) => [player.player_id, player]));
  const isComplete = (match) => match.ycac_goals !== "" && match.opponent_goals !== "";
  const tmlMatches = data.Matches.filter((match) => match.competition === "TML Division 3" && isComplete(match)).sort((a, b) => b.date.localeCompare(a.date));
  const friendlyMatches = data.Matches.filter((match) => match.competition === "Friendly Match" && isComplete(match)).sort((a, b) => b.date.localeCompare(a.date));
  const playedMatches = [...tmlMatches, ...friendlyMatches].sort((a, b) => b.date.localeCompare(a.date));
  const fixtures = data.Matches.filter((match) => !isComplete(match)).sort((a, b) => a.date.localeCompare(b.date));
  const setStats = (prefix, matches) => { const wins = matches.filter((match) => Number(match.ycac_goals) > Number(match.opponent_goals)).length; const draws = matches.filter((match) => Number(match.ycac_goals) === Number(match.opponent_goals)).length; const losses = matches.length - wins - draws; const record = document.querySelector(`#${prefix}-record`); record.innerHTML = `${wins}–${draws}–${losses}<small>${language === "ja" ? "勝-分-敗" : "W-D-L"}</small>`; record.setAttribute("aria-label", language === "ja" ? `${wins}勝 ${draws}分 ${losses}敗` : `${wins} wins, ${draws} draws, ${losses} losses`); document.querySelector(`#${prefix}-goals-for`).textContent = matches.reduce((total, match) => total + Number(match.ycac_goals), 0); document.querySelector(`#${prefix}-goals-against`).textContent = matches.reduce((total, match) => total + Number(match.opponent_goals), 0); document.querySelector(`#${prefix}-clean-sheets`).textContent = matches.filter((match) => Number(match.opponent_goals) === 0).length; };
  setStats("tml", tmlMatches); setStats("friendly", friendlyMatches);
  const friendlyLabel = language === "ja" ? "親善試合" : "Friendly Matches";
  document.querySelector("#friendly-title").textContent = friendlyLabel; document.querySelector("#friendly-results-label").textContent = friendlyLabel;
  document.querySelector("#updated").textContent = `${t("liveData")} · ${tmlMatches.length} ${t("matchesRecorded")}`;
  document.querySelector("#friendly-updated").textContent = `${friendlyMatches.length} ${t("matchesRecorded")}`;
  const visualLabels = language === "ja" ? { eyebrow: "ゴール", distribution: "得点ランキング", timeline: "シーズン結果", friendly: "親善試合", win: "勝", draw: "分", loss: "敗" } : { eyebrow: "Goals", distribution: "Top Scorers", timeline: "Results Timeline", friendly: "Friendly", win: "W", draw: "D", loss: "L" };
  document.querySelector("#distribution-eyebrow").textContent = visualLabels.eyebrow; document.querySelector("#distribution-title").textContent = visualLabels.distribution; document.querySelector("#timeline-eyebrow").textContent = language === "ja" ? "2026 シーズン" : "Season 2026"; document.querySelector("#timeline-title").textContent = visualLabels.timeline; document.querySelector("#friendly-timeline-label").textContent = visualLabels.friendly;
  const scorerTotals = (matches) => { const ids = new Set(matches.map((match) => match.match_id)); const totals = new Map(); for (const goal of data.Goals.filter((goal) => ids.has(goal.match_id))) totals.set(goal.scorer_id, (totals.get(goal.scorer_id) || 0) + 1); return [...totals.entries()].sort((a, b) => b[1] - a[1]); };
  const tmlScorers = scorerTotals(tmlMatches), friendlyScorers = scorerTotals(friendlyMatches), largestScorerTotal = Math.max(1, ...tmlScorers.map(([, goals]) => goals), ...friendlyScorers.map(([, goals]) => goals));
  const distribution = (label, scorers, competition) => `<div class="goal-group ${competition}"><div class="goal-group-head"><span>${label}</span><span>${scorers.reduce((total, [, goals]) => total + goals, 0)} ${t("goals")}</span></div><div class="goal-bars">${scorers.map(([id, goals]) => `<div class="goal-bar scorer-bar"><span>${playerName(players, id)}</span><div class="goal-track"><div class="goal-fill" style="width:${goals / largestScorerTotal * 100}%"></div></div><strong class="goal-value">${goals}</strong></div>`).join("")}</div></div>`;
  document.querySelector("#goal-distribution").innerHTML = distribution("TML Division 3", tmlScorers, "tml") + distribution(friendlyLabel, friendlyScorers, "friendly");
  document.querySelector("#season-timeline").innerHTML = playedMatches.map((match) => { const goalsFor = Number(match.ycac_goals), goalsAgainst = Number(match.opponent_goals); const outcome = goalsFor > goalsAgainst ? "win" : goalsFor === goalsAgainst ? "draw" : "loss"; return `<div class="timeline-entry ${match.competition === "Friendly Match" ? "friendly" : "tml"}"><div class="timeline-date">${formatDate(match.date)}</div><div class="timeline-rail"><i class="timeline-marker"></i></div><div class="timeline-match"><div class="timeline-opponent">${t("versus")} ${match.opponent}</div><div class="timeline-meta">${match.competition}</div></div><div class="timeline-score ${outcome}">${goalsFor}–${goalsAgainst}<span>${visualLabels[outcome]}</span></div></div>`; }).join("") || document.querySelector("#empty-state").innerHTML;
  document.querySelector("#fixtures").innerHTML = fixtures.map((match) => { const signups = `${match.standard_signup_url ? `<a href="${match.standard_signup_url}" target="_blank" rel="noreferrer">${t("standardSignup")}</a>` : ""}${match.priority_signup_url ? `<a href="${match.priority_signup_url}" target="_blank" rel="noreferrer">${t("prioritySignup")}</a>` : ""}`; return `<div class="fixture"><div class="fixture-date">${formatDate(match.date)}</div><div><div class="fixture-opponent">${t("versus")} ${match.opponent}</div><div class="fixture-meta">${match.competition}${match.venue ? ` · ${match.venue}` : ""}</div>${signups ? `<div class="fixture-actions">${signups}</div>` : ""}</div><div class="fixture-time">${match.kickoff || "TBC"}<br /><small>${t("kickoff")}</small></div></div>`; }).join("") || document.querySelector("#empty-state").innerHTML;
  const renderResults = (target, matches) => { document.querySelector(target).innerHTML = matches.map((match) => `<div class="match"><div class="match-date">${formatDate(match.date)}</div><div><div class="match-opponent">${t("versus")} ${match.opponent}</div><div class="match-meta">${match.venue || match.competition}</div></div><div class="match-score ${Number(match.ycac_goals) > Number(match.opponent_goals) ? "win" : ""}">${match.ycac_goals}–${match.opponent_goals}</div></div>`).join("") || document.querySelector("#empty-state").innerHTML; };
  renderResults("#tml-results", tmlMatches); renderResults("#friendly-results", friendlyMatches);
  const appearancesByMatch = new Map(data.Appearances.map((appearance) => [`${appearance.match_id}:${appearance.player_id}`, appearance]));
  const goalsByMatch = new Map(); for (const goal of data.Goals) { const key = `${goal.match_id}:${goal.scorer_id}`; goalsByMatch.set(key, (goalsByMatch.get(key) || 0) + 1); }
  const positionGroup = (position) => ({ GK: "GK", CB: "DF", LB: "DF", RB: "DF", LWB: "DF", RWB: "DF", DM: "MF", CM: "MF", AM: "MF", AMC: "MF", AMF: "MF", LW: "AT", RW: "AT", ST: "AT", CF: "AT", FW: "AT" })[position] || "Other";
  const positionOrder = { GK: 0, DF: 1, MF: 2, AT: 3, Other: 4 };
  const playerRows = [...players.values()].sort((a, b) => positionOrder[positionGroup(a.primary_position)] - positionOrder[positionGroup(b.primary_position)] || a.display_name.localeCompare(b.display_name));
  const playerSummary = (player, matches) => { const ids = new Set(matches.map((match) => match.match_id)); const appearances = matches.filter((match) => appearancesByMatch.has(`${match.match_id}:${player.player_id}`)).length; const goals = [...goalsByMatch.entries()].filter(([key]) => ids.has(key.split(":")[0]) && key.endsWith(`:${player.player_id}`)).reduce((total, [, value]) => total + value, 0); const cleanSheets = matches.filter((match) => player.primary_position === "GK" && appearancesByMatch.get(`${match.match_id}:${player.player_id}`)?.role === "starter" && Number(match.opponent_goals) === 0).length; const summary = [`${goals}⚽`, `${cleanSheets}🧤`].filter((value) => value[0] !== "0").join(" "); return `${appearances ? `${Math.round(appearances / matches.length * 100)}%` : "—"}${summary ? ` · ${summary}` : ""}`; };
  document.querySelector("#attendance-head").innerHTML = `<tr><th>${t("player")}</th><th>${t("position")}</th><th><span class="attendance-long">TML ${t("summary")}</span><span class="attendance-short">TML</span></th><th><span class="attendance-long">${friendlyLabel} ${t("summary")}</span><span class="attendance-short">FND</span></th>${playedMatches.map((match) => `<th class="match-column ${match.competition === "Friendly Match" ? "friendly-match" : "tml-match"}" title="${match.opponent}">${formatDate(match.date)}<small>${match.opponent}</small></th>`).join("")}</tr>`;
  document.querySelector("#attendance").innerHTML = playerRows.filter((player) => player.display_name.toLocaleLowerCase().includes(attendanceSearch)).map((player) => `<tr><td>${player.display_name}</td><td>${positionGroup(player.primary_position)}${player.primary_position && positionGroup(player.primary_position) !== player.primary_position ? ` · ${player.primary_position}` : ""}</td><td>${playerSummary(player, tmlMatches)}</td><td>${playerSummary(player, friendlyMatches)}</td>${playedMatches.map((match) => { const competitionClass = match.competition === "Friendly Match" ? "friendly-match" : "tml-match"; const appearance = appearancesByMatch.get(`${match.match_id}:${player.player_id}`); if (!appearance) return `<td class="match-cell empty-cell ${competitionClass}">—</td>`; const goals = goalsByMatch.get(`${match.match_id}:${player.player_id}`) || 0; const cleanSheet = player.primary_position === "GK" && appearance.role === "starter" && Number(match.opponent_goals) === 0; return `<td class="match-cell ${competitionClass}">${appearance.role === "starter" ? "🟢" : "🔵"}${"⚽".repeat(goals)}${cleanSheet ? "🧤" : ""}</td>`; }).join("")}</tr>`).join("");
}

applyLanguage();
document.querySelector("#attendance-search").addEventListener("input", (event) => { attendanceSearch = event.target.value.trim().toLocaleLowerCase(); if (dashboardData) render(dashboardData); });
Promise.all(tabs.map(async (tab) => [tab, await getSheet(tab)])).then((entries) => { dashboardData = Object.fromEntries(entries); render(dashboardData); }).catch((error) => { console.error(error); document.querySelector("#updated").textContent = t("unavailable"); });
