const sheetId = "1anWPcNxxjs9bMjxgwey9P8FNm4_usHGr";
const tabs = ["Players", "Matches", "Appearances", "Signups"];
const formations = { 433: [["AT", "AT", "AT"], ["MF", "MF", "MF"], ["DF", "DF", "DF", "DF"], ["GK"]], 4231: [["AT"], ["MF", "MF", "MF"], ["MF", "MF"], ["DF", "DF", "DF", "DF"], ["GK"]], 442: [["AT", "AT"], ["MF", "MF", "MF", "MF"], ["DF", "DF", "DF", "DF"], ["GK"]], 352: [["AT", "AT"], ["MF", "MF", "MF", "MF", "MF"], ["DF", "DF", "DF"], ["GK"]] };
const positionGroup = (position) => ({ GK: "GK", CB: "DF", LB: "DF", RB: "DF", LWB: "DF", RWB: "DF", DM: "MF", CM: "MF", AM: "MF", AMC: "MF", AMF: "MF", LW: "AT", RW: "AT", ST: "AT", CF: "AT", FW: "AT" })[position] || "Other";
const positionOrder = { GK: 0, DF: 1, MF: 2, AT: 3, Other: 4 };
let data, players = [], slots = [], substitutes = Array(9).fill(null), active = null, search = "";

function getSheet(tab) {
  const callback = `ycacPicker_${tab}_${Date.now()}`;
  const query = new URLSearchParams({ tqx: `out:json;responseHandler:${callback}`, sheet: tab });
  return new Promise((resolve, reject) => {
    const script = document.createElement("script");
    const cleanup = () => { script.remove(); delete window[callback]; };
    window[callback] = (response) => { cleanup(); if (response.status !== "ok") { reject(new Error(`Could not load ${tab}`)); return; } let headers = response.table.cols.map((column) => column.label), rows = response.table.rows; if (headers.every((header) => !header) && rows.length) { headers = rows[0].c.map((cell) => cell?.v ?? ""); rows = rows.slice(1); } resolve(rows.map((row) => Object.fromEntries(headers.map((header, index) => [header, row.c[index]?.v ?? ""])))); };
    script.onerror = () => { cleanup(); reject(new Error(`Could not load ${tab}`)); };
    script.src = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?${query}`;
    document.head.append(script);
  });
}

function selectedEvent() { return data.Matches.find((match) => match.match_id === document.querySelector("#event").value); }
function isPast(match) { return match.ycac_goals !== "" && match.opponent_goals !== ""; }
function availablePlayerIds() { const match = selectedEvent(); if (!match) return new Set(); if (isPast(match)) return new Set(data.Appearances.filter((appearance) => appearance.match_id === match.match_id).map((appearance) => appearance.player_id)); return new Set(data.Signups.filter((signup) => signup.match_id === match.match_id && !["declined", "out", "unavailable"].includes(String(signup.status).toLowerCase())).map((signup) => signup.player_id)); }
function eventPlayers() { const ids = availablePlayerIds(); return players.filter((player) => ids.has(player.player_id)); }
function setStatus(text) { document.querySelector("#picker-status").textContent = text; }

function resetFormation() { slots = formations[document.querySelector("#formation").value].flat().map((role, index) => ({ id: index, role, playerId: null })); substitutes = Array(9).fill(null); active = null; document.querySelector("#formation-name").textContent = document.querySelector("#formation").selectedOptions[0].text; render(); }
function assignToStarter(playerId, preferredRole) { const target = slots.find((slot) => !slot.playerId && slot.role === preferredRole) || slots.find((slot) => !slot.playerId); if (target) target.playerId = playerId; return Boolean(target); }
function historicalScore(playerId, role) { const pastAppearances = data.Appearances.filter((appearance) => appearance.player_id === playerId); return pastAppearances.reduce((score, appearance) => score + (appearance.role === "starter" ? 3 : 1) + (positionGroup(appearance.position) === role ? 2 : 0), 0); }
function suggestSquad() { resetFormation(); const available = eventPlayers().sort((a, b) => historicalScore(b.player_id, positionGroup(b.primary_position)) - historicalScore(a.player_id, positionGroup(a.primary_position))); for (const slot of slots) { const candidate = available.find((player) => !slots.some((item) => item.playerId === player.player_id) && positionGroup(player.primary_position) === slot.role); if (candidate) slot.playerId = candidate.player_id; }
  const chosen = new Set(slots.map((slot) => slot.playerId).filter(Boolean)); available.filter((player) => !chosen.has(player.player_id)).slice(0, 9).forEach((player, index) => { substitutes[index] = player.player_id; }); setStatus("Suggested from past appearances. Review and adjust the XI and bench."); render(); }
function loadPastLineup() { resetFormation(); const match = selectedEvent(); const appearances = data.Appearances.filter((appearance) => appearance.match_id === match.match_id); appearances.filter((appearance) => appearance.role === "starter").forEach((appearance) => assignToStarter(appearance.player_id, positionGroup(appearance.position || players.find((player) => player.player_id === appearance.player_id)?.primary_position))); appearances.filter((appearance) => appearance.role !== "starter").slice(0, 9).forEach((appearance, index) => { substitutes[index] = appearance.player_id; }); setStatus("Recorded lineup loaded. Adjust it if needed."); render(); }
function changeEvent() { const match = selectedEvent(); if (!match) return; if (isPast(match)) loadPastLineup(); else { resetFormation(); setStatus(eventPlayers().length ? "Confirmed sign-ups loaded. Use Suggest squad or select players." : "No confirmed sign-ups yet. Add confirmed players to the Signups sheet."); } }

function renderPitch() { const rows = [], formation = formations[document.querySelector("#formation").value]; let cursor = 0; for (const row of formation) { const rowSlots = slots.slice(cursor, cursor + row.length); cursor += row.length; rows.push(`<div class="pitch-row">${rowSlots.map((slot) => { const player = players.find((item) => item.player_id === slot.playerId); return `<button class="slot ${player ? "assigned" : ""} ${active?.area === "start" && active.index === slot.id ? "active" : ""}" type="button" data-slot="${slot.id}">${player ? `<span class="slot-number">${player.shirt_number || ""}</span><span class="slot-name">${player.display_name}</span>` : `<span class="slot-role">${slot.role}</span>`}</button>`; }).join("")}</div>`); } document.querySelector("#pitch").innerHTML = rows.join(""); document.querySelectorAll(".slot").forEach((button) => button.addEventListener("click", () => { active = { area: "start", index: Number(button.dataset.slot) }; setStatus(`Select a player for this ${slots[active.index].role} slot.`); render(); })); }
function renderBench() { document.querySelector("#bench").innerHTML = substitutes.map((playerId, index) => { const player = players.find((item) => item.player_id === playerId); return `<button class="bench-slot ${player ? "assigned" : ""} ${active?.area === "bench" && active.index === index ? "active" : ""}" type="button" data-bench="${index}"><span class="bench-index">${index + 1}</span><span class="bench-name">${player ? player.display_name : "Open substitute"}</span></button>`; }).join(""); document.querySelector("#bench-count").textContent = substitutes.filter(Boolean).length; document.querySelectorAll(".bench-slot").forEach((button) => button.addEventListener("click", () => { active = { area: "bench", index: Number(button.dataset.bench) }; setStatus("Select a player for this substitute slot."); render(); })); }
function allSelected() { return new Set([...slots.map((slot) => slot.playerId), ...substitutes].filter(Boolean)); }
function renderRoster() { const selected = allSelected(); const visible = eventPlayers().filter((player) => player.display_name.toLocaleLowerCase().includes(search)); const groups = ["GK", "DF", "MF", "AT", "Other"]; document.querySelector("#roster").innerHTML = groups.map((group) => { const members = visible.filter((player) => positionGroup(player.primary_position) === group); if (!members.length) return ""; return `<section class="roster-group"><h3>${group}</h3><div class="player-list">${members.map((player) => `<button class="player-card ${selected.has(player.player_id) ? "selected" : ""}" type="button" data-player="${player.player_id}"><span class="player-number">${player.shirt_number || "–"}</span><span class="player-name">${player.display_name}</span><span class="player-position">${player.primary_position || group}</span></button>`).join("")}</div></section>`; }).join("") || `<p class="loading">No eligible players for this event yet.</p>`; document.querySelectorAll(".player-card").forEach((button) => button.addEventListener("click", () => assignPlayer(button.dataset.player))); }
function assignPlayer(playerId) { slots.forEach((slot) => { if (slot.playerId === playerId) slot.playerId = null; }); substitutes = substitutes.map((id) => id === playerId ? null : id); const player = players.find((item) => item.player_id === playerId); if (active?.area === "start") slots[active.index].playerId = playerId; else if (active?.area === "bench") substitutes[active.index] = playerId; else if (!assignToStarter(playerId, positionGroup(player.primary_position))) { const index = substitutes.findIndex((id) => !id); if (index >= 0) substitutes[index] = playerId; else { setStatus("The 20-player matchday squad is full. Select a slot to replace a player."); render(); return; } } active = null; setStatus(`${player.display_name} added to the matchday squad.`); render(); }
function renderOutput() { const starting = slots.filter((slot) => slot.playerId).map((slot) => players.find((player) => player.player_id === slot.playerId).display_name); const bench = substitutes.filter(Boolean).map((id) => players.find((player) => player.player_id === id).display_name); document.querySelector("#selected-count").textContent = starting.length + bench.length; document.querySelector("#lineup-output").textContent = starting.length ? `${document.querySelector("#formation").selectedOptions[0].text} Starting XI: ${starting.join(" · ")}${bench.length ? ` | Subs: ${bench.join(" · ")}` : ""}` : "Your selected XI will appear here."; }
function render() { renderPitch(); renderBench(); renderRoster(); renderOutput(); }
function populateEvents() { const select = document.querySelector("#event"); const matches = [...data.Matches].sort((a, b) => a.date.localeCompare(b.date)); select.innerHTML = matches.map((match) => `<option value="${match.match_id}">${match.date} · ${match.opponent} · ${match.competition}</option>`).join(""); const upcoming = matches.find((match) => !isPast(match)); select.value = (upcoming || matches[matches.length - 1]).match_id; }
function saveSquadImage() { if (!allSelected().size) { setStatus("Select at least one player before saving an image."); return; } const canvas = document.createElement("canvas"), context = canvas.getContext("2d"), width = 1200, height = 1200, field = { x: 70, y: 180, width: 700, height: 880 }; canvas.width = width; canvas.height = height; context.fillStyle = "#081a35"; context.fillRect(0, 0, width, height); context.fillStyle = "#c5a059"; context.font = "700 26px DM Sans, Arial"; context.fillText("YC&AC PULSE", 70, 72); context.fillStyle = "#ffffff"; context.font = "400 52px Georgia"; context.fillText("Matchday Squad", 70, 130); context.font = "600 22px DM Sans, Arial"; context.fillStyle = "#d8e2f2"; context.fillText(`${document.querySelector("#formation").selectedOptions[0].text}  ·  ${selectedEvent().date}  ·  vs ${selectedEvent().opponent}`, 70, 160); context.fillStyle = "#367c54"; context.fillRect(field.x, field.y, field.width, field.height); context.strokeStyle = "rgba(255,255,255,.85)"; context.lineWidth = 3; context.strokeRect(field.x + 12, field.y + 12, field.width - 24, field.height - 24); context.beginPath(); context.moveTo(field.x + 12, field.y + field.height / 2); context.lineTo(field.x + field.width - 12, field.y + field.height / 2); context.stroke(); context.beginPath(); context.arc(field.x + field.width / 2, field.y + field.height / 2, 70, 0, Math.PI * 2); context.stroke(); const formation = formations[document.querySelector("#formation").value]; let cursor = 0; formation.forEach((row, rowIndex) => { row.forEach((role, playerIndex) => { const slot = slots[cursor++]; const player = players.find((item) => item.player_id === slot.playerId); const x = field.x + field.width * (playerIndex + 1) / (row.length + 1), y = field.y + 80 + (field.height - 160) * rowIndex / Math.max(formation.length - 1, 1); context.fillStyle = player ? "#f4ecdc" : "rgba(8,26,53,.55)"; context.beginPath(); context.arc(x, y, 35, 0, Math.PI * 2); context.fill(); context.fillStyle = player ? "#112950" : "#ffffff"; context.font = "700 15px DM Sans, Arial"; context.textAlign = "center"; context.fillText(player ? player.display_name : role, x, y + 5); }); }); context.textAlign = "left"; context.fillStyle = "#c5a059"; context.font = "700 20px DM Sans, Arial"; context.fillText("SUBSTITUTES", 835, 225); context.fillStyle = "#ffffff"; context.font = "400 25px Georgia"; substitutes.forEach((id, index) => { const player = players.find((item) => item.player_id === id); context.fillText(`${String(index + 1).padStart(2, "0")}  ${player?.display_name || "Open"}`, 835, 280 + index * 58); }); context.fillStyle = "#d8e2f2"; context.font = "600 16px DM Sans, Arial"; context.fillText(`${allSelected().size} / 20 PLAYERS SELECTED`, 835, 930); const link = document.createElement("a"); link.download = `ycac-pulse-${selectedEvent().date}-squad.png`; link.href = canvas.toDataURL("image/png"); link.click(); setStatus("Squad image saved."); }

document.querySelector("#formation").addEventListener("change", resetFormation);
document.querySelector("#event").addEventListener("change", changeEvent);
document.querySelector("#suggest-squad").addEventListener("click", suggestSquad);
document.querySelector("#clear-squad").addEventListener("click", () => { resetFormation(); setStatus("Squad cleared."); });
document.querySelector("#player-search").addEventListener("input", (event) => { search = event.target.value.trim().toLocaleLowerCase(); renderRoster(); });
document.querySelector("#copy-squad").addEventListener("click", async () => { if (!allSelected().size) return; try { await navigator.clipboard.writeText(`YC&AC Pulse Matchday Squad\n${document.querySelector("#lineup-output").textContent}`); setStatus("Lineup copied to your clipboard."); } catch { setStatus("Copy is unavailable in this browser."); } });
document.querySelector("#save-image").addEventListener("click", saveSquadImage);
Promise.all(tabs.map(async (tab) => [tab, await getSheet(tab).catch((error) => { if (tab === "Signups") return []; throw error; })])).then((entries) => { data = Object.fromEntries(entries); players = data.Players.filter((player) => player.active !== false).sort((a, b) => positionOrder[positionGroup(a.primary_position)] - positionOrder[positionGroup(b.primary_position)] || a.display_name.localeCompare(b.display_name)); populateEvents(); changeEvent(); }).catch(() => { document.querySelector("#roster").innerHTML = `<p class="loading">The squad data could not be loaded. Please try again.</p>`; });
